# Generated by Django 4.1.4 on 2022-12-17 10:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_api', '0003_alter_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('date_of_birth', models.DateField()),
                ('photo', models.ImageField(upload_to='employee_photos/')),
                ('position', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('salary', models.DecimalField(decimal_places=2, max_digits=6)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_api.company')),
            ],
        ),
    ]
