# Generated by Django 4.1.4 on 2022-12-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_api', '0002_alter_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='uploads/default.jpg', upload_to='company_logos/'),
        ),
    ]
