# Generated by Django 4.1.4 on 2022-12-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_api', '0003_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='company_logos/default.jpg', upload_to='company_logos/'),
        ),
    ]
